spring:
 datasource:
  url: jdbc:mysql://localhost:3306/employee_db
  username: root
  password: mySQL123
  
 jpa:
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect
  hibernate:
   ddl-auto: update
   
server:
 port: 8081
 
eureka:
 instance:
  client:
   serverUrl:
    defaultZone: http://localhost:8761/eureka/
